### ISSUE TITLE
Generating custom key pairs

### ISSUE THREAD

**Issue by spleenware** [ShubhamAnnigeri/tinyECC-ArduinoIDE#4]
Is there a way to generate custom private/public key pairs? Looks like the library has hard-coded ones.

**Comment by ShubhamAnnigeri** [comment]
Hi spleenware. I have written a code in C that you can use to generate custom private-public key pairs. I'll upload it as a separate repository soon and post its link in the comments.
I've hard-coded the key pairs in the library because I wanted them to be as lightweight as possible. Calculating the public key for a given private key and base point is a computationally intensive task for a controller like Arduino that has limited memory. I would recommend that use the C code to generate key pairs you want to use and hardcode them into the library for better performance.

**Comment by ShubhamAnnigeri** [comment]
Hi @spleenware. You can check the latest repository I've uploaded for the full code base of ECC.
https://github.com/ShubhamAnnigeri/ECC-Full-Code-Base
